// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message
type UpperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         []byte `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                 //request ID
	ReqType    string `protobuf:"bytes,2,opt,name=reqType,proto3" json:"reqType,omitempty"`       //请求类型
	ReqContent []byte `protobuf:"bytes,3,opt,name=reqContent,proto3" json:"reqContent,omitempty"` //请求内容
}

func (x *UpperRequest) Reset() {
	*x = UpperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpperRequest) ProtoMessage() {}

func (x *UpperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpperRequest.ProtoReflect.Descriptor instead.
func (*UpperRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *UpperRequest) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *UpperRequest) GetReqType() string {
	if x != nil {
		return x.ReqType
	}
	return ""
}

func (x *UpperRequest) GetReqContent() []byte {
	if x != nil {
		return x.ReqContent
	}
	return nil
}

// The response message
type UpperReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReaType []byte `protobuf:"bytes,1,opt,name=reaType,proto3" json:"reaType,omitempty"` //响应类型
	Contnet []byte `protobuf:"bytes,2,opt,name=contnet,proto3" json:"contnet,omitempty"` //响应内容
}

func (x *UpperReply) Reset() {
	*x = UpperReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpperReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpperReply) ProtoMessage() {}

func (x *UpperReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpperReply.ProtoReflect.Descriptor instead.
func (*UpperReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *UpperReply) GetReaType() []byte {
	if x != nil {
		return x.ReaType
	}
	return nil
}

func (x *UpperReply) GetContnet() []byte {
	if x != nil {
		return x.Contnet
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0c, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x40, 0x0a, 0x0a, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x72, 0x65, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x6e,
	0x65, 0x74, 0x32, 0x7e, 0x0a, 0x0a, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x77,
	0x12, 0x36, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x70, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x70, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []interface{}{
	(*UpperRequest)(nil), // 0: proto.UpperRequest
	(*UpperReply)(nil),   // 1: proto.UpperReply
}
var file_message_proto_depIdxs = []int32{
	0, // 0: proto.SingleFlow.PutMessage:input_type -> proto.UpperRequest
	0, // 1: proto.SingleFlow.GetMessage:input_type -> proto.UpperRequest
	1, // 2: proto.SingleFlow.PutMessage:output_type -> proto.UpperReply
	1, // 3: proto.SingleFlow.GetMessage:output_type -> proto.UpperReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpperReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SingleFlowClient is the client API for SingleFlow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SingleFlowClient interface {
	// 推送服务器消息
	PutMessage(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperReply, error)
	// 获取服务器消息
	GetMessage(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (SingleFlow_GetMessageClient, error)
}

type singleFlowClient struct {
	cc grpc.ClientConnInterface
}

func NewSingleFlowClient(cc grpc.ClientConnInterface) SingleFlowClient {
	return &singleFlowClient{cc}
}

func (c *singleFlowClient) PutMessage(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (*UpperReply, error) {
	out := new(UpperReply)
	err := c.cc.Invoke(ctx, "/proto.SingleFlow/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *singleFlowClient) GetMessage(ctx context.Context, in *UpperRequest, opts ...grpc.CallOption) (SingleFlow_GetMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SingleFlow_serviceDesc.Streams[0], "/proto.SingleFlow/GetMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &singleFlowGetMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SingleFlow_GetMessageClient interface {
	Recv() (*UpperReply, error)
	grpc.ClientStream
}

type singleFlowGetMessageClient struct {
	grpc.ClientStream
}

func (x *singleFlowGetMessageClient) Recv() (*UpperReply, error) {
	m := new(UpperReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SingleFlowServer is the server API for SingleFlow service.
type SingleFlowServer interface {
	// 推送服务器消息
	PutMessage(context.Context, *UpperRequest) (*UpperReply, error)
	// 获取服务器消息
	GetMessage(*UpperRequest, SingleFlow_GetMessageServer) error
}

// UnimplementedSingleFlowServer can be embedded to have forward compatible implementations.
type UnimplementedSingleFlowServer struct {
}

func (*UnimplementedSingleFlowServer) PutMessage(context.Context, *UpperRequest) (*UpperReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMessage not implemented")
}
func (*UnimplementedSingleFlowServer) GetMessage(*UpperRequest, SingleFlow_GetMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}

func RegisterSingleFlowServer(s *grpc.Server, srv SingleFlowServer) {
	s.RegisterService(&_SingleFlow_serviceDesc, srv)
}

func _SingleFlow_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SingleFlowServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SingleFlow/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SingleFlowServer).PutMessage(ctx, req.(*UpperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SingleFlow_GetMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpperRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SingleFlowServer).GetMessage(m, &singleFlowGetMessageServer{stream})
}

type SingleFlow_GetMessageServer interface {
	Send(*UpperReply) error
	grpc.ServerStream
}

type singleFlowGetMessageServer struct {
	grpc.ServerStream
}

func (x *singleFlowGetMessageServer) Send(m *UpperReply) error {
	return x.ServerStream.SendMsg(m)
}

var _SingleFlow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SingleFlow",
	HandlerType: (*SingleFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutMessage",
			Handler:    _SingleFlow_PutMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMessage",
			Handler:       _SingleFlow_GetMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}
